### ISSUE TITLE
Arduino Library Manager

### ISSUE THREAD

**Issue by don** [adafruit/Adafruit_BME280_Library#1]
Can you add this to the Arduino Library Manger?

**Comment by tdicola** [comment]
Oh thanks for the reminder, I just added the metadata it needs and put an issue on Arduino to add them.  Can follow it here: https://github.com/arduino/Arduino/issues/3710  Once they resolve it in a few days it should get picked up a few hours later.

**Comment by don** [comment]
Thanks Tony
