### ISSUE TITLE
I2C to USB

### ISSUE THREAD

**Issue by Bra1nsen** [adafruit/Adafruit_BME280_Library#103]
Question:

How can i read out the bme280 with i2c-->usb on a raspy?

![image](https://user-images.githubusercontent.com/58213050/167086616-5333d68e-b9ca-4c49-99d8-82474b7339d8.png)

**Comment by caternuson** [comment]
https://learn.adafruit.com/circuitpython-libraries-on-any-computer-with-mcp2221
https://learn.adafruit.com/circuitpython-on-any-computer-with-ft232h
https://learn.adafruit.com/circuitpython-libraries-on-any-computer-with-raspberry-pi-pico

or just connect directly to pi:
https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/python-circuitpython-test#python-computer-wiring-2994989-5
