### ISSUE TITLE
Commented out code: Purpose of Adafruit_BME280_Unified?

### ISSUE THREAD

**Issue by mozzbozz** [adafruit/Adafruit_BME280_Library#12]
The header file [contains](https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.h#L105) some commented out code which is there since the initial commit - there's no comment or whatsoever explaining the purpose of it. Is is just a TODO?

This is the code:

``` c++
/*
class Adafruit_BME280_Unified : public Adafruit_Sensor
{
  public:
    Adafruit_BME280_Unified(int32_t sensorID = -1);
    bool  begin(uint8_t addr = BME280_ADDRESS);
    void  getTemperature(float *temp);
    void  getPressure(float *pressure);
    float pressureToAltitude(float seaLevel, float atmospheric, float temp);
    float seaLevelForAltitude(float altitude, float atmospheric, float temp);
    void  getEvent(sensors_event_t*);
    void  getSensor(sensor_t*);
  private:
    uint8_t   _i2c_addr;
    int32_t   _sensorID;
};
*/
```

As the "unified" stuff seems to be just some mocking, there doesn't seem to be any need for the `#include <Adafruit_Sensor.h>` either? At least removing it from both the `Adafruit_BME280.h`-file and the `bme280test.ino` example sketch gets rid of the following warning at compile time:

> warning: unused parameter 'enabled' in virtual void enableAutoRange(bool enabled) {};

and at least for me it doesn't seem to break anything. But I think the code author will know better than me about the reasons for this code segment...

**Comment by ladyada** [comment]
its a 'todo' for us to get around to Unifying all our sensors to be standardized. no need for it at this time, just ignore it :)
