### ISSUE TITLE
Missing Adafruit_Sensor.h

### ISSUE THREAD

**Issue by swisssam** [adafruit/Adafruit_BME280_Library#18]
I downloaded the library and found it missing Adafruit_Sensor.h included in the example and the main library header. Since I did not find any hints and it seems not needed I removed the include statements. To resolve the issue I would like to have either the include statements removed or a link to the file provided in the readme file.

**Comment by microbuilder** [comment]
Closed with https://github.com/adafruit/Adafruit_BME280_Library/commit/0e1d97a603e5f0f96642d872caeeebdf1c55bc03
