### ISSUE TITLE
Is it possible to return absolute humidity instead of relative?

### ISSUE THREAD

**Issue by yucandu** [adafruit/Adafruit_BME280_Library#22]
I was looking at the code for readHumidity, and it looks like it first takes a temperature reading then implements this into the humidity reading formula.  Does this mean the BME280 is actually outputting absolute humidity, and the code is converting that to relative?

Because I much prefer absolute humidity, and in my code I am taking this relative humidity value, and the temperature value, and converting it to absolute.  But if the BME280 sensor itself can output absolute in the first place, I wouldn't need to do this inaccurate equation.

**Comment by ladyada** [comment]
we follow the datasheet instruction, check those for any calculations and what they measure preciesly :)
