### ISSUE TITLE
Example sketch will not compile - SPI Class missing member

### ISSUE THREAD

**Issue by CristoXeuari** [adafruit/Adafruit_BME280_Library#25]
- Arduino board:  Uno

- Arduino IDE version:  Arduino 2:1.0.5+dfsg2-4

- Issue: The example sketch <i>bme280test</i> will not compile, the compiler complains...

> /home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp: In member function ‘void Adafruit_BME280::write8(byte, byte)’:
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:158:17: error: ‘class SPIClass’ has no member named ‘beginTransaction’
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                 ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:158:73: error: ‘SPISettings’ was not declared in this scope
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                                                                         ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:164:13: error: ‘class SPIClass’ has no member named ‘endTransaction’
         SPI.endTransaction(); // release the SPI bus
             ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp: In member function ‘uint8_t Adafruit_BME280::read8(byte)’:
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:185:17: error: ‘class SPIClass’ has no member named ‘beginTransaction’
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                 ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:185:73: error: ‘SPISettings’ was not declared in this scope
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                                                                         ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:191:17: error: ‘class SPIClass’ has no member named ‘endTransaction’
             SPI.endTransaction(); // release the SPI bus
                 ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp: In member function ‘uint16_t Adafruit_BME280::read16(byte)’:
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:214:17: error: ‘class SPIClass’ has no member named ‘beginTransaction’
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                 ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:214:73: error: ‘SPISettings’ was not declared in this scope
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                                                                         ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:220:17: error: ‘class SPIClass’ has no member named ‘endTransaction’
             SPI.endTransaction(); // release the SPI bus
                 ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp: In member function ‘uint32_t Adafruit_BME280::read24(byte)’:
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:282:17: error: ‘class SPIClass’ has no member named ‘beginTransaction’
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                 ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:282:73: error: ‘SPISettings’ was not declared in this scope
             SPI.beginTransaction(SPISettings(500000, MSBFIRST, SPI_MODE0));
                                                                         ^
/home/xeuari/sketchbook/libraries/Adafruit_BME280_Library/Adafruit_BME280.cpp:294:17: error: ‘class SPIClass’ has no member named ‘endTransaction’
             SPI.endTransaction(); // release the SPI bus
                 ^

My core libraries are up to date. Does the bme280 library use a previous SPI library release?

Thanks --Xeuari--

**Comment by ladyada** [comment]
arduino 1.0 is no longer supported, you must use 1.6+!
