### ISSUE TITLE
constructor should take a connection object instead of pinout list 

### ISSUE THREAD

**Issue by viknet365** [adafruit/Adafruit_BME280_Library#27]
The Adafruit_BME280 constructor take pins (SPI) or nothing (I2C/Wire) where it should take a full Wire object that could be use for connection with the BME (unsure about SPI) AND the adress 0x76 or 0x77 of the sensor.
This would enable usage of the librarie with different flavour of "SoftwareWire" (bitbanging I2C) and enable multiple I2C on one board (when you need more than 2 BME)

**Comment by ladyada** [comment]
i2c multisupport was added with this
https://github.com/adafruit/Adafruit_BME280_Library/pull/26#issuecomment-328938252

**Comment by viknet365** [comment]
Thanks, probably have some sort of Telepathy link with @mjs513
