### ISSUE TITLE
register struct issues 

### ISSUE THREAD

**Issue by j07rdi** [adafruit/Adafruit_BME280_Library#28]
Refer to this code inside the *.h file: 

`unsigned int get() { return (t_sb << 5) | (filter << 3) | spi3w_en;}`  

 `            unsigned int get() {
                return (osrs_t << 5) | (osrs_p << 3) | mode;
            }`

I'm sure the bit shift 3 for "filter" and "osrs_p" should be 2, otherwise, it will overlap the t_sb and osrs_t bits values.

**Comment by loadletter** [comment]
I've also noticed this while using a simulator
![registers](https://user-images.githubusercontent.com/5257054/34082536-87c066d8-e360-11e7-94a2-c25263a79d43.png)
