### ISSUE TITLE
have 2 BME280 by 0x76 and 0x77 simultaneously side by side on same i2c Bus?

### ISSUE THREAD

**Issue by tofrnr** [adafruit/Adafruit_BME280_Library#31]
how is it possible to have 2 BME280 by bus addresses 0x76 and 0x77 simultaneously side by side on same i2c Bus?
For that purpose the ability to create instances by passing the bus address would be helpful and then wiring CS to GND or Vc accordingly:
```
#include <Adafruit_Sensor.h>
#include <Adafruit_BME280.h>

Adafruit_BME280 bme1(0x76);  
Adafruit_BME280 bme2(0x77);  
```

will that be provided?

**Comment by ladyada** [comment]
addresses are called in to begin()
https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.cpp#L50

**Comment by tofrnr** [comment]
yes, but as stated: I need 2 addresses (0x76 and 0x77), simultaneously, for 2 devices! So how to have 2 arbitrary instances simultaneously?

**Comment by tofrnr** [comment]
why do you close this issue? 
it is not solved - how shall I call begin()  with 2 different device addresses??

**Comment by andrei-ivanov** [comment]
Probably because it's not a library issue, but a general coding issue :-)

**Comment by tofrnr** [comment]
so what is the solution - I don't see a chance to pass an address to begin() by value, resp. 2 different ones.
As long as it is not possible eventually, then it's a library issue.

**Comment by andrei-ivanov** [comment]
You were given a link to the method that allows to do that.
If you don't know how to invoke it, please try a coding guide.

**Comment by tofrnr** [comment]
I don't understand - in the link there is just the lib source code, what am I expected to do with that?
I want to use the lib, with 2 different addresses for 2 different instances simulaneously, so what to do?
If possible, show me, if not, it's a lib issue and the lib has to be improved.

**Comment by andrei-ivanov** [comment]
It's possible, just use Google

**Comment by ladyada** [comment]
hiya, the library should work - closing this issue because there's a way to do it just not at instantiation :) please only open issues for bugs, not tech support - please contact the company you bought the sensor from for tech support (adafruit has a forum for our customers)
