### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Gauthamjm007** [adafruit/Adafruit_BME280_Library#35]
Arduino: 1.6.9 (Windows 10), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 4M (3M SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"

WARNING: Spurious .github folder in 'Adafruit BME280 Library' library
WARNING: Spurious .github folder in 'ArduinoJson' library
C:\Users\Lenovo\AppData\Local\Temp\arduino_modified_sketch_467989\bme280test.ino:20:29: fatal error: Adafruit_Sensor.h: No such file or directory

 #include <Adafruit_Sensor.h>

                             ^

compilation terminated.

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ladyada** [comment]
install https://github.com/adafruit/Adafruit_Sensor

**Comment by Gauthamjm007** [comment]
Thank you
