### ISSUE TITLE
Error: 'Wire1' was not declared in this scope in  "advancedsettings" example from the Adafruit BME280 library

### ISSUE THREAD

**Issue by GeoffLethbridge** [adafruit/Adafruit_BME280_Library#36]
- Arduino board:  UNO

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.5

The "advancedsettings" example from the Adafruit BME280 library gives the following error:   
/----------------------------------
exit status 1
'Wire1' was not declared in this scope
/----------------------------------
Removing 'Wire1' ie bme.begin(&Wire1) -> bme.begin(), fixes the error and the example compiles OK.

**Comment by themanfrommoon** [comment]
Hi, I have the same Problem?!

**Comment by xxorde** [comment]
I saw the same error.
Looks like the name is different depending on your platform, have a look here: https://forums.adafruit.com/viewtopic.php?f=25&t=83304#p420627

Maybe there is some more elegant solution.

**Comment by nopnop2002** [comment]
Remove esp32 from board manager
Delete C:\Users\your_user\AppData\Local\Arduino15\packages\esp32
Install esp32 from board manager again.

**Comment by hoffmannjan** [comment]
Looks like the solution is well known, closing this.
