### ISSUE TITLE
multiple sensors

### ISSUE THREAD

**Issue by JensDerKrueger** [adafruit/Adafruit_BME280_Library#4]
I suggest to make the static member bme280_calib_data bme280_calib an object variable. Otherwise, running multiple sensors in one project returns incorrect data except for the one that wrote it's calibration data in to the static last.

**Comment by tdicola** [comment]
Thanks for the suggestion!  Yep that sounds like a great idea to avoid conflicts with multiple sensors and different calibration values.  Just submitted a change to make the calibration data a private class member.  Thanks!
