### ISSUE TITLE
Wrong link to store item

### ISSUE THREAD

**Issue by StephenHodgson** [adafruit/Adafruit_BME280_Library#45]
https://github.com/adafruit/Adafruit_BME280_Library/blob/24a162b0bb69577ad5dd5f1e81352ca3640344dd/Adafruit_BME280.cpp#L14

Should be https://www.adafruit.com/product/2652

**Comment by ladyada** [comment]
@hoffmannjan plz check!

**Comment by hoffmannjan** [comment]
fixed :)
