### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kankaristo** [adafruit/Adafruit_BME280_Library#50]
The repository doesn't have a LICENSE or COPYING file, which license is the library distributed under?

If it's up for a vote, I'd suggest MIT or some other permissive license.

**Comment by kankaristo** [comment]
Just noticed that the source files mention the BSD license.

I'll leave this issue open for now, since most people probably look for the license in either a file called LICENSE or COPYING.

**Comment by siddacious** [comment]
@kankaristo thanks for the feedback; If you wanted to submit a PR I'd be happy to review it

**Comment by kankaristo** [comment]
I'd be happy to make a PR, but there are actually a few different versions of the BSD license, and the license mention in the source files don't specify which one:
- 2 clause BSD
- 3 clause BSD ("New BSD")
- 4 clause BSD ("Original BSD")

The 4 clause BSD license is considered "problematic", because it includes a clause that all marketing material must include this sentence verbatim:
> This product includes software developed by the University of California, Berkeley and its contributors.

So, that leaves the 2 clause and the 3 clause licenses. The only difference between those licenses is this clause:
> Neither the name of nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

The 3 clause license is probably more common, and if you ask for permission to "promote" the fact that your software uses Adafruit libraries, the 2 and 3 clause licenses are identical. And the line between "promotion/endorsement" and simple "acknowledgement" is up for debate.

I'll make a PR for the 3 clause BSD license + mention of the LICENSE file in the source files.

**Comment by kankaristo** [comment]
PR created:
https://github.com/adafruit/Adafruit_BME280_Library/pull/51

**Comment by siddacious** [comment]
closed via PR #51
