### ISSUE TITLE
BME280.begin() does not support specifying custom I2C pins

### ISSUE THREAD

**Issue by lnlp** [adafruit/Adafruit_BME280_Library#58]
Adafruit BME280.begin() does not support specifying custom pins for I2C. 
(While for SPI specifying custom pins is supported.)

ESP32 supports 2 hardware I2C interfaces but BME280 library can only be used for the default I2C pins because custom I2C pins cannot be specified.

Please add an option for specifying custom I2C pins when calling BME280.begin().

**Comment by lnlp** [comment]
After further investigation this can be solved without a change to BME280.begin().

**Comment by stodge** [comment]
How did you solve this?

**Comment by caternuson** [comment]
Check here:
https://github.com/espressif/arduino-esp32/issues/3779

**Comment by Cristianistrate** [comment]
> Check here: [espressif/arduino-esp32#3779](https://github.com/espressif/arduino-esp32/issues/3779)

Can you specify exactly how  ?
SetPins is working ?
Thank you.
