### ISSUE TITLE
Missing feature, sleep mode.

### ISSUE THREAD

**Issue by liba2k** [adafruit/Adafruit_BME280_Library#6]
Hi,
Can you please implement a way to send the BME to sleep mode?
Something like:

void Adafruit_BME280::stop() {
  write8(BME280_REGISTER_CONTROL, 0);
}

Thank you,
Itai.

**Comment by mozzbozz** [comment]
Related (implements the features you are looking for): https://github.com/adafruit/Adafruit_BME280_Library/issues/8
Newer PR (improvement of the first PR): https://github.com/adafruit/Adafruit_BME280_Library/pull/13

**Comment by solars** [comment]
is this still open? I notice that sparkfun already has this for quite some time so I might switch

**Comment by Elfe** [comment]
in my code I reset the chip after reading the data to reduce power usage
without reset the esp32 + sensor is at about 350µA with the ESP32 in deep sleep
with reset the esp32 + sensor is at about 12µA

a public reset function would be nice

read stuff...
I2Cbus.beginTransmission(BMX280_ADDRESS);
I2Cbus.write(0xE0);
I2Cbus.write(0xB6);
I2Cbus.endTransmission();
sleep

**Comment by hoffmannjan** [comment]
this functionality is fully tested in master now :). thanks guys!

**Comment by solars** [comment]
@hoffmannjan is this documented somewhere?

**Comment by hoffmannjan** [comment]
@solars I'll add proper doxygen in this repo next week probably, but for now there is some hints in the code 
https://github.com/adafruit/Adafruit_BME280_Library/pull/13/files#diff-35e01fdd369e009c1e031cd9e83dac0bR169
and you can also look at whole comments section at  #13

**Comment by sergerold** [comment]
> @solars I'll add proper doxygen in this repo next week probably, but for now there is some hints in the code
> https://github.com/adafruit/Adafruit_BME280_Library/pull/13/files#diff-35e01fdd369e009c1e031cd9e83dac0bR169
> and you can also look at whole comments section at #13

Please could someone confirm which method to use for sleep mode? Should I be setting MODE_FORCED? If so, where?

Thanks
