### ISSUE TITLE
To high delay in init() method

### ISSUE THREAD

**Issue by marcin1mn** [adafruit/Adafruit_BME280_Library#64]
Why in init() method is so big delay?
https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.cpp#L147
https://github.com/adafruit/Adafruit_BME280_Library/blob/master/Adafruit_BME280.cpp#L151

I tested witch 25 delay on ESP8266 and is also fine.
It's wasting energy of battery.

**Comment by ladyada** [comment]
hiya please check the datasheet to see if there's a wake up time required

**Comment by marcin1mn** [comment]
As you can see on datasheet, BME280 requires only 2ms to start up.
Page number: 7
https://cdn-shop.adafruit.com/datasheets/BST-BME280_DS001-10.pdf

**Comment by ladyada** [comment]
ok try changing it to 5 ms :)
