### ISSUE TITLE
BME280_ADDRESS_ALTERNATE does nothing

### ISSUE THREAD

**Issue by mordv** [adafruit/Adafruit_BME280_Library#74]
I had to change the address from 0x77 to 0x76 and I found an interesting constant BME280_ADDRESS_ALTERNATE.
But I can't find any usage of it in code

I suppose, it either must be removed totally or implemented as in (#68)

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_BME280_Library/blob/master/examples/bme280test/bme280test.ino#L47
