### ISSUE TITLE
Software Wire / I2C

### ISSUE THREAD

**Issue by bobemoe** [adafruit/Adafruit_BME280_Library#83]
Hi, is there any plan (or guides) on adding support for software wire so other Arduino pins can be used for I2C connection? I see we can pass our on Wire object into constructor, but this is not compatible with software wire. Looks like I could fork and hack it in but just checking this isn't already supported or something? Many thanks.

**Comment by ladyada** [comment]
no plans, we only support hardware i2c for our libraries!

**Comment by bobemoe** [comment]
I've managed to hack it in using https://github.com/felias-fogg/SlowSoftWire , I guess you're not interested in a PR then?

**Comment by ladyada** [comment]
its best to keep in your fork, thanks !
